apiVersion: apps/v1
kind: Deployment
metadata:
  name: formipro
  labels:
    app: formipro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formipro
  template:
    metadata:
      labels:
        app: formipro
    spec:
      containers:
        - name: formipro
          image: ci.local:5000/formipro:latest
          ports:
            - containerPort: 22222