name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Export Release Timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d%H')" >> $GITHUB_ENV
    - name: Build and push docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: nguyen99/formipro-backend:${{ env.TIMESTAMP }}, nguyen99/formipro-backend:latest
